apiVersion: skaffold/v2alpha1
kind: Config
profiles:
  - name: local-dev
    activation:
      - kubeContext: docker-desktop
      - command: run
    build:
      local:
        push: false
      artifacts:
        - image: schachte/my-devops35
          jib: {}
    deploy:
      kubectl:
        manifests:
          - k8s/*
