apiVersion: skaffold/v2alpha1
kind: Config
profiles:
  - name: local-dev
    activation:
      - kubeContext: docker-desktop
    build:
      tagPolicy:
        gitCommit: {}
      local:
        push: false
      artifacts:
        - image: schachte/devops-demo
          jib: {}
    deploy:
      kubectl:
        manifests:
          - k8s/*
